[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"
  node_bundler = "esbuild"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

